### ISSUE TITLE
InCommon: explicit <mdrpi:RegistrationInfo> elements will be added to InCommon metadata

### ISSUE THREAD

**Issue by trscavo** [iay/mdq-server-docker#14]
This is just a heads up!

InCommon Operations will add explicit `<mdrpi:RegistrationInfo>` elements to production metadata according to the following schedule:

1. preview aggregate: Wed, Feb 4, 2015
2. main aggregate: Wed, Feb 11, 2015
3. fallback aggregate: Web, Feb 18, 2015

I assume the mdq-server instance at mdq-beta.incommon.org is consuming the main (production) aggregate, in which case the middle date above is most relevant.

**Comment by iay** [comment]
I believe this will be OK, as the current configuration adds this element only if it is not already present. I will verify that this is the case, however, between the 4th and 11th.

**Comment by iay** [comment]
Confirmed that the existing configuration for `mdq-beta` works with the current InCommon preview aggregate today. I therefore believe that the `mdq-beta` deployment will cope just fine when the production aggregate transitions, but of course we will want to verify that after the change goes live.

**Comment by iay** [comment]
The InCommon production aggregate transitioned on 2015-02-12; current plan for the fallback aggregate is to transition on 2015-02-19. I'll remove the redundant stage some time after that and before the next deployment cycle.

**Comment by iay** [comment]
Transition has occurred with no problems, removing the redundant code is issue #16.
